### ISSUE TITLE
Replace CPU virtualization modules with virt86

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/StrikeBox#19]
[virt86](https://github.com/StrikerX3/virt86) provides an abstraction of x86 virtualization platforms originally based on StrikeBox's CPU abstraction framework. It has improved and fixed many bugs (for example, WHPX now initializes correctly) and is likely to be improved by the community.

**Comment by PatrickvL** [comment]
HAXM might recieve AMD support through a Google Summer Of Code project, possibly mentored by @AlexAltea (main contributor amongst many things to the Experimental PlayStation 4 emulator https://github.com/AlexAltea/orbital)

**Comment by StrikerX3** [comment]
Very good! Both StrikeBox and virt86 will benefit from that. Let's hope it gets approved.

**Comment by StrikerX3** [comment]
virt86 has been integrated. It fixes WHPX support, adds HAXM on Mac OS X and lots of improvements across the board. The CPU modules infrastructure is no longer in use too.
