### ISSUE TITLE
Add support for Windows Hypervisor Platform

### ISSUE THREAD

**Issue by StrikerX3** [StrikerX3/StrikeBox#2]
[Windows Hypervisor Platform](https://docs.microsoft.com/en-us/virtualization/api/hypervisor-platform/hypervisor-platform) is a virtualization platform based on Microsoft's Hyper-V released with the April 2018 Update for Windows 10. It must be enabled manually from the Windows Features panel.

We want to implement this as a Windows-only CPU module.

**Comment by StrikerX3** [comment]
WHPX needs a bit of work to initialize properly. As of now, it starts in 16-bit mode with CS:EIP set to F000:FFF0, which points to 0x000FFFF0 in 32-bit address space, which is taken by RAM. This is incorrect. The problem lies in the base address of the CS register, which is set to 0x000F0000 instead of 0xFFFF0000 and, according to Intel's manuals, the latter is the correct value.

**Comment by Ale100000** [comment]
Windows Hypervisor Platform is also avaliable for Windows 10 Home.

**Comment by StrikerX3** [comment]
> Windows Hypervisor Platform is also avaliable for Windows 10 Home.

Good to know. Thanks.

By the way, this issue will be solved once the CPU virtualization modules are replaced with virt86 (#19).

**Comment by StrikerX3** [comment]
#19 supersedes this.
